Repository cri-o/packaging, pull requests merged in 2023-10, with the labels that each got.

#9 Retry `vagrant up`
  scripts/helpers
  scripts/obs
  scripts/test-kubernetes
Labels: kind/ci, approved, dco-signoff: yes, release-note-none

#10 Add shfmt and shellcheck to CI
  .github/workflows/test.yml
  Makefile
  dependencies.yaml
Labels: kind/ci, approved, dco-signoff: yes, lgtm, release-note-none

#11 Use binary release of `krel`
  dependencies.yaml
  scripts/helpers
  scripts/obs
Labels: kind/ci, approved, dco-signoff: yes, lgtm, release-note-none

#12 Remove unused caches
  .github/workflows/obs.yml
Labels: kind/cleanup, dco-signoff: yes, release-note-none

#13 Update krel to v0.16.2 and auto-wait
  dependencies.yaml
  scripts/helpers
  scripts/obs
Labels: kind/feature, approved, dco-signoff: yes, lgtm, release-note-none

#15 Add new blog post
  README.md
Labels: kind/documentation, approved, dco-signoff: yes, lgtm, release-note-none

#16 Update krel to v0.16.3
  dependencies.yaml
  scripts/helpers
  scripts/obs
Labels: kind/cleanup, approved, dco-signoff: yes, lgtm, release-note-none

#19 Make the two Vagrantfiles a little more similar
  README.md
  test/deb/Vagrantfile
  test/rpm/Vagrantfile
Labels: kind/cleanup, approved, dco-signoff: yes, lgtm, release-note-none

#17 Use registries.conf.d instead of main registries.conf
  templates/latest/cri-o/cri-o.spec
Labels: kind/feature, approved, dco-signoff: yes, lgtm, release-note

#22 Remove dependency on containernetworking-plugins
  templates/latest/cri-o/cri-o.spec
  test/rpm/Dockerfile
Labels: kind/cleanup, approved, dco-signoff: yes, lgtm, release-note-none

#21 Add lima.yaml as an alternative to Vagrantfile
  test/deb/lima.yaml
  test/rpm/lima.yaml
Labels: kind/feature, approved, dco-signoff: yes, lgtm, release-note

#24 Set process_gcloudignore: false
  .github/workflows/obs.yml
Labels: kind/ci, approved, dco-signoff: yes, release-note-none

#26 Fix systemd unit path
  templates/latest/cri-o/cri-o.spec
Labels: dco-signoff: yes, kind/bug, release-note-none

#27 Update crun to 1.10
  dependencies.yaml
  templates/latest/cri-o/bundle/versions
Labels: kind/feature, approved, dco-signoff: yes, lgtm, release-note-none

#28 Move get script into this repository
  .github/workflows/obs.yml
  .github/workflows/test.yml
  .gitignore
  Makefile
  dependencies.yaml
  get
  scripts/tree-status
Labels: kind/feature, approved, dco-signoff: yes, lgtm, release-note

#30 Let bundle marker universally work
  .github/workflows/obs.yml
Labels: kind/ci, approved, dco-signoff: yes, lgtm, release-note-none

#33 Use CentOS Stream 9 for Vagrant tests
  dependencies.yaml
  test/rpm/Vagrantfile
Labels: kind/ci, approved, dco-signoff: yes, lgtm, release-note-none

#29 Add docs about static binary bundles
  README.md
Labels: kind/documentation, approved, dco-signoff: yes, lgtm, release-note-none

#32 Reuse environment vars and wait for GitHub actions to avoid races
  .github/workflows/obs.yml
  scripts/bundle/build
  scripts/github-job-wait
  scripts/obs
  scripts/vars
Labels: kind/ci, approved, dco-signoff: yes, lgtm, release-note-none

#37 Remove `crio-status` binary
  get
  scripts/bundle/build
  templates/latest/cri-o/bundle/install
Labels: approved, dco-signoff: yes, lgtm, release-note

#38 Bump crun to v1.11
  dependencies.yaml
  templates/latest/cri-o/bundle/versions
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note-none
