Repository cri-o/packaging, pull requests merged in 2023-11, with the labels that each got.

#39 Use CentOS Stream for rpm lima yaml
  test/rpm/lima.yaml
Labels: kind/cleanup, approved, dco-signoff: yes, lgtm, release-note-none

#41 Bump crun to v1.11.1
  dependencies.yaml
  templates/latest/cri-o/bundle/versions
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note

#42 Fix archive identifier for stable versions
  scripts/bundle/build
Labels: kind/failing-test, approved, dco-signoff: yes, release-note-none

#40 Bump runc to v1.1.10
  dependencies.yaml
  templates/latest/cri-o/bundle/versions
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note

#43 Simplify pod and container JSON
  dependencies.yaml
  scripts/bundle/test
  test/testdata/container.json
  test/testdata/container_redis.json
  test/testdata/pod.json
  test/testdata/sandbox_config.json
Labels: kind/cleanup, approved, dco-signoff: yes, lgtm, release-note-none

#44 Fix RPM box url
  .github/workflows/obs.yml
  scripts/helpers
  test/rpm/Vagrantfile
Labels: kind/ci, approved, dco-signoff: yes, lgtm, release-note-none

#45 Disable vagrant based tests for now
  .github/workflows/obs.yml
Labels: kind/failing-test, approved, dco-signoff: yes, lgtm, release-note-none

#47 Update zeitgeist to v0.4.3
  Makefile
  dependencies.yaml
Labels: kind/ci, approved, dco-signoff: yes, lgtm, release-note-none

#48 Run `release` step independent from test-kubernetes
  .github/workflows/obs.yml
Labels: kind/failing-test, approved, dco-signoff: yes, lgtm, release-note-none

#46 Update crun to 1.11.2
  dependencies.yaml
  templates/latest/cri-o/bundle/versions
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note-none

#49 Update krel to v0.16.4
  dependencies.yaml
  scripts/helpers
Labels: kind/ci, approved, dco-signoff: yes, lgtm, release-note-none

#50 Re-enable Vagrant based tests
  .github/workflows/obs.yml
Labels: kind/failing-test, approved, dco-signoff: yes, lgtm, release-note-none

#52 Update crun to 1.12
  dependencies.yaml
  templates/latest/cri-o/bundle/versions
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note-none

#51 Switch to Ubuntu based Vagrant tests
  .github/workflows/obs.yml
  scripts/github-actions-setup
  scripts/test-kubernetes
  test/deb/Vagrantfile
  test/deb/lima.yaml
  test/rpm/Vagrantfile
  test/rpm/lima.yaml
Labels: kind/ci, approved, dco-signoff: yes, release-note-none
