Repository cri-o/packaging, pull requests merged in 2024-05, with the labels that each got.

#94 Update conmon to v2.1.11
  dependencies.yaml
  templates/latest/cri-o/bundle/versions
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note-none

#95 Update zeitgeist to v0.5.3
  Makefile
  dependencies.yaml
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note-none

#96 Enable s390x in tests
  .github/workflows/obs.yml
Labels: kind/ci, approved, dco-signoff: yes, lgtm, release-note-none

#97 Bump crun to v1.15
  dependencies.yaml
  templates/latest/cri-o/bundle/versions
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note-none

#99 Add v1.31 package streams
  README.md
Labels: kind/documentation, approved, dco-signoff: yes, lgtm, release-note-none

#102 Fix amount of files in bundle
  scripts/bundle/build
Labels: kind/failing-test, approved, dco-signoff: yes, lgtm, release-note-none

#103 Build packages 1h after possible CRI-O releases
  .github/workflows/schedule.yml
Labels: kind/ci, approved, dco-signoff: yes, lgtm, release-note-none

#105 Explicitly set runtime_root in the default config
  templates/latest/cri-o/bundle/10-crio.conf
Labels: approved, dco-signoff: yes, lgtm, release-note

#107 Add `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: kind/documentation, approved, dco-signoff: yes, lgtm, release-note-none

#111 Update cni-plugins to v1.5.0
  dependencies.yaml
  scripts/bundle/build
  templates/latest/cri-o/bundle/versions
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note-none

#110 Update conmon to v2.1.12
  dependencies.yaml
  templates/latest/cri-o/bundle/versions
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note-none

#112 Refactor vagrant integration tests
  dependencies.yaml
  test/deb/Vagrantfile
  test/rpm/Vagrantfile
  test/scripts/install-deb.sh
  test/scripts/install-rpm.sh
  test/scripts/test.sh
  test/scripts/versions.sh
Labels: kind/ci, approved, dco-signoff: yes, lgtm, release-note-none

#113 Refactor Docker integration tests
  scripts/test-architectures
  test/deb/Dockerfile
  test/rpm/Dockerfile
  test/scripts/install-deb.sh
  test/scripts/install-rpm.sh
  test/scripts/versions.sh
Labels: kind/ci, approved, dco-signoff: yes, lgtm, release-note-none
