Repository cri-o/packaging, pull requests merged in 2025-02, with the labels that each got.

#217 Mark v1.29 as EOL
  README.md
Labels: kind/documentation, approved, dco-signoff: yes, lgtm, release-note-none

#219 Update crun to 1.20
  dependencies.yaml
  templates/latest/cri-o/bundle/versions
Labels: kind/cleanup, approved, dco-signoff: yes, lgtm, release-note-none

#221 Switch to new OBS subprojects
  README.md
  scripts/reconcile
  scripts/vars
  test/deb/lima.yaml
  test/rpm/lima.yaml
  test/scripts/install-deb.sh
  test/scripts/install-rpm.sh
Labels: kind/documentation, approved, dco-signoff: yes, lgtm, release-note-none

#223 CRI-O is no longer a subproject of Kubernetes
  README.md
Labels: kind/documentation, approved, dco-signoff: yes, lgtm, release-note-none

#222 Update runc to v1.2.5
  dependencies.yaml
  templates/latest/cri-o/bundle/versions
Labels: kind/ci, approved, dco-signoff: yes, lgtm, release-note-none

#226 Fix docs `:` vs `.`
  README.md
Labels: kind/documentation, approved, dco-signoff: yes, lgtm, release-note-none

#227 Update krel to v0.18.0
  dependencies.yaml
  scripts/helpers
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note-none

#229 Update conmon to v2.1.13
  dependencies.yaml
  templates/latest/cri-o/bundle/versions
Labels: approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note-none
