Repository cri-o/packaging, pull requests merged in 2025-06, with the labels that each got.

#257 Fix osc permission error.
  dependencies.yaml
  scripts/helpers
Labels: kind/ci, approved, dco-signoff: yes, kind/dependency-change, lgtm, release-note-none

#259 fix verify command
  get
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#264 Fix prettier run in CI
  README.md
Labels: kind/failing-test, approved, dco-signoff: yes, lgtm, release-note-none
